### PR TITLE
Update cgal to 5.0.0

### PR DESCRIPTION
**Pull request by Michsior14**
Updates to the next major version of CGAL.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by Michsior14** [comment]
conda-forge-admin, please rerender

**Comment by Michsior14** [comment]
@conda-forge-admin, please rerender

**Comment by Michsior14** [comment]
There seems to be some problems with tests prefix for linux and osx:

```sh
TEST START: /home/conda/feedstock_root/build_artifacts/linux-64/cgal-cpp-5.0-h261e690_0.tar.bz2
Renaming work directory,  /home/conda/feedstock_root/build_artifacts/cgal-cpp_1573428680913/work  to  /home/conda/feedstock_root/build_artifacts/cgal-cpp_1573428680913/work_moved_cgal-cpp-5.0-h261e690_0_linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/conda/feedstock_root/build_artifacts/cgal-cpp_1573428680913/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
.
.
.
export PREFIX=/home/conda/feedstock_root/build_artifacts/cgal-cpp_1573428680913/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/cgal-cpp_1573428680913/test_tmp
INFO: activate-binutils_linux-64.sh made the following environmental changes:
.
.
.
+GXX=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-g++
+ test -f /home/conda/feedstock_root/build_artifacts/cgal-cpp_1573428680913/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/CGAL/AABB_tree.h
+ test -f /home/conda/feedstock_root/build_artifacts/cgal-cpp_1573428680913/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libCGAL.so
Tests failed for cgal-cpp-5.0-h261e690_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for cgal-cpp-5.0-h261e690_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING conda_build.build:tests_failed(2231): Tests failed for cgal-cpp-5.0-h261e690_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: cgal-cpp-5.0-h261e690_0.tar.bz2
##[error]Bash exited with code '1'.
```

**Comment by Michsior14** [comment]
@tadeu Is there any chance to review it today?

**Comment by Michsior14** [comment]
@conda-forge-admin, please rerender

**Comment by Michsior14** [comment]
@tadeu Any news regarding the review?

**Comment by ocefpaf** [comment]
> @tadeu Any news regarding the review?

@tadeu is far more knowledgeable here to provide a proper review. Let's wait for him.

**Comment by tadeu** [comment]
Ouch, so sorry for the late reply, it looks good, I'm merging it!
Thanks @Michsior14

**Comment by ostrokach** [comment]
@Michsior14 @tadeu Is there a reason why we are no longer providing the `libCGAL.so` file and why the following test was removed:

```
test -f ${PREFIX}/lib/libCGAL${SHLIB_EXT}  # [unix]
```

**Comment by tadeu** [comment]
According to @Michsior14 [comment above](https://github.com/conda-forge/cgal-cpp-feedstock/pull/7#issuecomment-552247839):

> the new CGAL version is [header only by default](https://doc.cgal.org/latest/Manual/installation.html)

**Comment by ostrokach** [comment]
That explains it. Thank you!

**Pull request merged**
