### PR TITLE
Update cgal to 5.0.3

### PR DESCRIPTION
**Pull request by Michsior14**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Update to CGAL 5.0.3.

### CODE REVIEW

**Comment by Michsior14** [comment]
@conda-forge-admin, please rerender

**Comment by Michsior14** [comment]
@tadeu `boost` hasn't been found on `win_64`, could you have a look?

**Comment by Michsior14** [comment]
Hey @tadeu :) Do you have any more ideas regarding `win` issue?

**Comment by tadeu** [comment]
Oh, it worked, but the `-DBoost_USE_STATIC_LIBS=OFF ` flag is now required at the library user side :(

People will probably have trouble when updating it, but at least the CMake error is clear on what should be done.

**Comment by tadeu** [comment]
Thanks @Michsior14, I'll merge this

**Pull request merged**
