### PR TITLE
Update CGAL to 4.14.1

### PR DESCRIPTION
**Pull request by Michsior14**
Updates to the bugfixed version of CGAL 4.14.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] ~~Ensured the license file is being packaged.~~

### CODE REVIEW

**Comment by Michsior14** [comment]
I have no idea why the build failed on osx and win. Looks like some kind of pipeline problem?

**Comment by tadeu** [comment]
On Windows it looks like `%CMAKE_GENERATOR%` can't be used on Azure, the workaround is to use NMake:

https://github.com/conda-forge/conda-forge.github.io/issues/703#issuecomment-509557120

I'll try changing that

**Comment by tadeu** [comment]
About macOS, I have no idea why `conda` isn't able to extract a simple .zip file:

```
libarchive.exception.ArchiveError: Could not open CGAL-4.14.1 (errno=14, retcode=-30, archive_p=140209583138080)
```

**Comment by tadeu** [comment]
Thanks @Michsior14

**Pull request merged**
